### ISSUE TITLE
groupdate was resolved to 4.3.0, which depends on Ruby (>= 2.4)

### ISSUE THREAD

**Issue by kinan53** [vteams/open-source-billing#92]
I tried to install this framework as the commands you gave in the page .. all things went good but on installing bundle this error came up and i don't know how to solve this ...  please help !
![issue](https://user-images.githubusercontent.com/59497160/71760793-35050300-2ee9-11ea-96ff-c943b79cea3e.png)

**Comment by pepeva1012** [comment]
hey, this issue is resolved? i have the same issue

**Comment by kinan53** [comment]
no its not resolved... actually they are not replying or taking interest in
this issue.. i will suggest you to go with invoiceNinja .. its much better
and they reply so quickly for any issue .

**Comment by alexanderadam** [comment]
The problem is, that the resolved dependencies are not clear.
In the Ruby community there's usually an easy solution for that, called [`Gemfile.lock` that will be checked in and then everything is clear for the dependency resolver bundler](https://bundler.io/v1.3/rationale.html#checking-your-code-into-version-control).

In this particular project the file is _not_ checked in, however. You can only find the `Gemfile` in it (without the `.lock` extension). This means that every installation might lead to _different_ resolvings and therefore some issues like yours can appear.
I [mentioned this once in issue 87](https://github.com/vteams/open-source-billing/issues/87) already but @shahzadtariq-nxb / @mshahzadtariq* is usually _closing_ and _forgetting_ about those issues.
I criticised this behaviour in [issue 90](https://github.com/vteams/open-source-billing/issues/90) as well.

The dependency situation would also be easier if they would provide a reproducible Docker image ([issue 58](https://github.com/vteams/open-source-billing/issues/58)). But [this request](https://github.com/vteams/open-source-billing/issues/58#event-1070566328) was closed and forgotten in 2017 as well.

*I'm still curious why he is using _two_ accounts.

**Comment by poudelprakash** [comment]
@alexanderadam could you please share your working Gemfile.lock file for this project, so that at least others can use the app for now until maintainers decide to resolve this

**Comment by alexanderadam** [comment]
I haven't it running at the moment and therefore I have none. Sorry.

**Comment by shahzadtariq-nxb** [comment]
Thank you @alexanderadam for your continuous contribution. I look forward to get more suggestions / feedback from you in future.
